server:
    servlet:
        context-path: /dddsample

cxf:
    path: /ws

logging:
    level:
        org.hibernate.SQL: info
        net.sf.ehcache.config.ConfigurationFactory: error

uploadDirectory: /tmp/upload
parseFailureDirectory: /tmp/failed

brokerUrl: "vm://localhost?broker.persistent=false&broker.useJmx=false"

spring:
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    dataSource:
        db_name: oauth
        driver_class: com.mysql.cj.jdbc.Drive
        url: jdbc:mysql://192.168.10.169:3306/oauth?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
        username: root
        password: xsq123456